This test does not seem to be ready for precommit tests.
It fails with
not ok 1 - use Treex::Tool::Lexicon::DerivDict::Dictionary;
#   Failed test 'use Treex::Tool::Lexicon::DerivDict::Dictionary;'
#   at /ha/work/people/popel/tectomt/treex/lib/Treex/Tool/Lexicon/DerivDict/t/deriv_dict_general.t line 7.
#     Tried to use 'Treex::Tool::Lexicon::DerivDict::Dictionary'.
#     Error:  Global symbol "$source_lexeme" requires explicit package name at /home/popel/tmt/treex/lib/Treex/Tool/Lexicon/DerivDict/Dictionary.pm line 58.
# syntax error at /home/popel/tmt/treex/lib/Treex/Tool/Lexicon/DerivDict/Dictionary.pm line 58, near "$source_lexeme}"
# Unmatched right curly bracket at /home/popel/tmt/treex/lib/Treex/Tool/Lexicon/DerivDict/Dictionary.pm line 62, at end of line
# syntax error at /home/popel/tmt/treex/lib/Treex/Tool/Lexicon/DerivDict/Dictionary.pm line 62, near "}"
# Can't use global @_ in "my" at /home/popel/tmt/treex/lib/Treex/Tool/Lexicon/DerivDict/Dictionary.pm line 69, near "= @_"
# Compilation failed in require at (eval 4) line 2.
# BEGIN failed--compilation aborted at (eval 4) line 2.
Can't locate object method "lexemes" via package "Treex::Tool::Lexicon::DerivDict::Dictionary" at /home/popel/tmt/treex/lib/Treex/Tool/Lexicon/DerivDict/Dictionary.pm line 36.
# Tests were run but no plan was declared and done_testing() was not seen.


git-svn-id: https://svn.ms.mff.cuni.cz/svn/tectomt_devel/trunk/treex@9726 7cf035df-8472-40d0-8fbe-a733a24d2855